config/routes.rb
Rails.application.routes.draw do
  get 'homepage', to: "homepage#index"
  
  get 'user', to: 'users#profile'

  get 'sessions/new'
  get '/register', to: 'users#new'
  resources :users, only: [:create]

  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  get 'search', to:'search#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do 
    resources :comments
  end
  root "posts#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post 
	
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user 
	has_many :comments, dependent: :destroy

	def self.ransackable_attributes(auth_object = nil)
    	["content", "created_at", "id", "title", "updated_at", "user_id"]
  	end

  	def self.ransackable_associations(auth_object = nil)
    	["comments", "user"]
  	end
end

app/models/user.rb
class User < ApplicationRecord
	# email validation to ensure the same email does not have more than 1 account
	validates :email, uniqueness: true

	# email validation to ensure an email is entered at the time of registration
	validates :email, presence: true

	# password validations to add entropy to passwords and make sure the length is at least 5
	validates :password, length: { minimum: 5, allow_nil: true }

	# defining the relationship between users and posts
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy

	def password
		@password
	end

	#encrypts the password
	def password=(raw)
		@password = raw
		self.password_digest = BCrypt::Password.create(raw)
	end

	#checks if the raw password is equal to the encrypted password
	def is_password?(raw)
		BCrypt::Password.new(password_digest).is_password?(raw)
	end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	before_action :set_query
		
	def set_query
		@q = Post.ransack(params[:q])
	end

	def ensure_current_user
		if current_user.nil?
			redirect_to "/"
		end
	end

	def index
	end

	def current_user
		if session[:user_id]
			User.find(session[:user_id])
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@post = Post.find(params[:post_id])
	@post.user = current_user
	@comment = @post.comments.create(params[:comment].permit(:name, :comment))
	redirect_to post_path(@post)
end

def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment.destroy
	redirect_to post_path(@post)
end



end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :ensure_current_user

  def index
    @posts = current_user.posts 
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show 
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to post_path

  end



  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :title, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	#ensuring a user is logged in before allowing them to view posts
	before_action :ensure_current_user

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.new(post_params)
		@post.user = current_user


		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show 
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end

	end

	def edit
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to post_path

	end



	private

	def set_post
		@post = current_user.posts.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:name, :title, :content)
	end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # lookup the user in the database
    @user = User.find_by(email: user_params[:email])

    if @user && @user.is_password?(user_params[:password]) 
      session[:user_id] = @user.id 
      redirect_to posts_path
    else
      flash[:notice] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #create a new user 
  def new
    @user = User.new
  end

  def profile
    @posts = @user.posts.order(created_at: :desc)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash.now[:notice] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
	<article class="media">
		<div class="media-content">
			<div class="content">
				<p>
					<strong><%= comment.comment %></strong>
				</p>
			</div>
			<div>
				<h4>posted by <%= link_to current_user.name, homepage_path(comment.user_id) %> at <%= comment.updated_at %></h4>
			</div>
			
		</div>

		<%= button_to 'Delete Comment', post_path(comment.post, comment), method: :delete, class: "button is-danger", form: { data: { turbo_confirm: 'Are you sure?' } } %>
	</article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	
	<div class="field">
		<div class="control">
			<%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>
	<%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/homepage/index.html.erb
<% content_for :page_title, "My Blog" %>

<div class="container mt-5">
	<div class="row">
		<div class="col-4">
			<%= @posts.each do |post| %>
				<div class="card mt-3">
					<div class="card-body">
						<h5 class="card-title"><%= link_to post.title, post %></h5>
						<p class="card-text"><%= post.content %></p>
						<p class="card-text"><%= post.created_at %> </p>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if current_user %>
      Hi <%= current_user.email %>
    <% end %>
    <title>
      <% if current_user %>
        <%= current_user.email %>'s Blog
      <% end %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
  <section class="hero is-primary is-medium">
    <div class="hero-head">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <% if current_user %>
              <%= link_to 'My Blog', homepage_path, class: "navbar-item" %>
            <% end %>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
              <% if current_user %>
                <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
              <% end %>
            </div>
            <div class="navbar-end">
              <% if current_user %>
                <%= link_to "Newsfeed", root_path %>
              <% end %> 
            </div>
            <div class="navbar-end">
              <% if current_user %>
                <%= link_to "Log out", sign_out_path %>
              <% end %>  
            </div>
          </div>
        </div>
      </nav>
    </div>


    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          <%= yield :page_title %>
        </h1>
      </div>

    </div>
  </section>
    <div class="container has-text-right">
        <%= render 'search/form' %>
    </div>

    <%= yield %>
  </body>

</html>

app/views/posts/_form.html.erb
<div class="section">
	<%= simple_form_for @post do |f| %>
	<div class="field">
		<div class="control">
			<%= f.input :title, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>
	<div class="field">
		<div class="control">
			<%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>
	<%= f.button :submit, class: "button is-primary" %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "News Feed" %>


<section class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
				<div class="card-content">
					<div class="media">
						<div class="media-content">
							<p class="title is-4"><%= link_to post.title, post %> </p>
						</div>
					</div>
					<div class="content">
						<%= post.content %>
					</div>
					<div>
						<h4>posted by <%= link_to post.user.name, homepage_path(post.user) %> at <%= post.updated_at %></h4>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>


<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>


<section class="section">
	<div class="container">
		<nav class="level">
			<!-- Left side -->
			<div class="level-left">
				<p class="level-item">
					<strong>Actions</strong>
				</p>
			</div>

			<!-- Right side -->
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit", edit_post_path(@post), class: "button" %>
				</p>
				<p class="level-item">
				<%= button_to 'Delete Post', post_path(@post), method: :delete, class: "button is-danger", form: { data: { turbo_confirm: 'Are you sure?' } } %>
				</p>
			</div>
		</nav>
		<hr/>

		<div class="content">
			<%= @post.content %>
		</div>
	</div>
</section>

<section class="section comments">
	<div class="container">
		<h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
		<%= render @post.comments %>
		<div class="comment-form">
			<hr />
			<h3 class="subtitle is-3">Leave a reply</h3>
	 		<%= render 'comments/form' %>
		</div>
	</div>
</section>

app/views/search/_form.html.erb
<%= search_form_for(@q, url: search_path, method: :get, class:'d-flex') do |f| %>
	<%= f.search_field :title_or_content_cont, placeholder: "Search...", class: "form-control me-2" %>
	<%= f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<% content_for :page_title, "Search Results" %>

<strong>
<h1 class="text-center"><%= pluralize(@posts.count, "Result") %></h1>
</strong> 


<div class="container">
	<table class="table table-dark table-striped">
		<thead>
			<tr>
				<th>
					<%= sort_link(@q, :title, "Title", default_order: :asc) %>
				</th>
				<th>
					<%= sort_link(@q, :content, "Blog Content") %>
				</th>
				<th>
					<%= sort_link(@q, :user, "Users") %>
				</th>
			</tr>
		</thead>

		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td><%= link_to post.title, post %></td>
					<td><%= post.content.truncate_words(25) %></td>
					
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/new.html.erb
<% content_for :page_title, "Register" %>
<p = id="notice"><%= notice %></p>

<!-- form for new user registration -->
<form action="/users" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

	<label for="name">Name</label>
	<input type="name" id="name" name="user[name]" value="<%= @user.name %>" />

	<label for="email">Email</label>
	<input type="email" id="email" name="user[email]" value="<%= @user.email %>" />

	<br />

	<label for="password">Password</label>
	<input type="password" id="password" name="user[password]" />

	<br />

	<input type="submit" value="Register">
</form>

app/views/users/profile.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-4">
			
		</div>
	</div>
</div>

<h1><%= @user.name %></h1>
<div>
<p>Find me in app/views/users/profile.html.erb</p>
</div>